Consider the below code to answer further questions:

In [2]:
import numpy as np
list_ = [ '1', '2', '3', '4', '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Answer: Of course, there are differences. The first one is a lost. On the other hand, the second one is a numpy "n" dimensional array. Here is the code:

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [ ]:
Answer: Here is the code:

In [9]:
# Print data types of elements in list_
for item in list_:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
# Print data types of elements in array_list
for item in array_list:
    print(type(item))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

In [11]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Answer: Yes, there will be a difference in the data type of the elements. Here is the code:

In [12]:
# Print data types of elements in list_
for item in list_:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
# Print data types of elements in array_list
for item in array_list:
    print(type(item))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


As you can see, the data types of the elements in array_list have changed to numpy.int64 after converting them to integers.

Consider the below code to answer further questions:

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

Answer: To find the characteristics of the num_array variable, you can use the following code:

In [16]:
# (i) Shape of the array
print("Shape:", num_array.shape)

# (ii) Size of the array
print("Size:", num_array.size)


Shape: (2, 3)
Size: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

Answer: Here is the code:

In [17]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Answer: Here is the code:

In [18]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
